### PR TITLE
Add support for updating FPM config on domain rename

### PR DESCRIPTION
**Pull request by iliarostovtsev**
Hi, Jamie.

Check this commit out. It adds support for changing PHP directives on domain's home directory rename.

Ref.:
https://forum.virtualmin.com/t/session-problems-after-domain-name-change/113348

### CODE REVIEW

**Comment by iliarostovtsev** [comment]
Perhaps, **`restore_web`** needs to call it too?

**Comment by jcameron** [comment]
Thanks for the patch!

**Comment by iliarostovtsev** [comment]
Should we merge it?

**Comment by iliarostovtsev** [comment]
Also, I think **`restore_web`** needs this new function call as well, right, Jamie?

**Pull request merged**
