### PR TITLE
More updates to env setting position

### PR DESCRIPTION
**Pull request by Harm133**
More swapping around of lines so the env variables get set at the correct time to allow custom scripts to run.
No extra logic has been added.

### CODE REVIEW

**Comment by jcameron** [comment]
That shouldn't be necessary - when Webmin is installed, it will update all .cgi and .pl scripts to use the correct path.

**Comment by Harm133** [comment]
Without these changes this:

$oldchain = &get_website_ssl_file($d, 'ca');

Wont run properly.

**Comment by jcameron** [comment]
I'm confused ... how does that `$oldchain` line fail exactly?

**Comment by Harm133** [comment]
It fails on my setup at least, it doesn't properly open the file. If I make those changes it works correctly. Same goes for newkey.cgi btw.

**Pull request closed without merging**
