### PR TITLE
Add support for PHP7.2 et future 7.3

### PR DESCRIPTION
**Pull request by herewithme**

### CODE REVIEW

**Comment by herewithme** [comment]
Related topic forum : 
https://www.virtualmin.com/node/54816#comment-790421

**Comment by jcameron** [comment]
Thanks!

**Comment by herewithme** [comment]
👍

**Comment by valentinogagliardi** [comment]
@herewithme thank you for this PR! I'm the OP of https://www.virtualmin.com/node/54816

**Comment by herewithme** [comment]
@valentinogagliardi ;)

**Comment by jicao** [comment]
Thanks 👍

**Pull request merged**
