### PR TITLE
Add support for username in transfers

### PR DESCRIPTION
**Pull request by iliajie**

### CODE REVIEW

**Comment by jcameron** [comment]
I already have code in progress to add username support ..

**Comment by iliajie** [comment]
Well, then it's up to you. You can close it ..

**Comment by jcameron** [comment]
Ok I checked in my version here : https://github.com/virtualmin/virtualmin-gpl/commit/fa9ba7686e17457c4ad827019936b24667d3b614

**Comment by iliajie** [comment]
Thanks! I think having an extra separate field is better.

**Pull request closed without merging**
