### PR TITLE
Remove download immediately option

### PR DESCRIPTION
**Pull request by iliajie**
I propose deleting this (download immediately) option as it requires opening a new tab, can hang for quite some time on large backups without showing any progress.

### CODE REVIEW

**Comment by jcameron** [comment]
Maybe let's wait until the next release, as the "download via link" option hasn't launched yet, and there may be bugs.

**Comment by iliarostovtsev** [comment]
Sounds reasonable. Although, I have tried "download via link" option many times and never experienced any issues.

**Comment by jcameron** [comment]
Let's wait till after this release.

**Comment by iliajie** [comment]
Let's remove it already?

**Comment by jcameron** [comment]
Have we had a release that included the new "download via link" feature?

**Comment by iliajie** [comment]
Yes, it's already been with Virtualmin 7.1 release for a while.

**Pull request merged**
