### PR TITLE
Fix not to leak personal details when crating default self-signed SSL certificate

### PR DESCRIPTION
**Pull request by iliajie**
Hey Jamie!

This patch ensures that private details won't be leaked when automatically generating a self-signed SSL certificate.

### CODE REVIEW

**Comment by jcameron** [comment]
I'm not opposed to this PR, but wouldn't the same thing happen when generating an LE cert?

**Comment by iliajie** [comment]
> I'm not opposed to this PR, but wouldn't the same thing happen when generating an LE cert?

What thing? Let's Encrypt doesn't add user email or any other potentially personal details. The description for the user can be private in nature.

**Comment by jcameron** [comment]
Oh right .. in that case, this looks fine to me.

**Comment by marclaporte** [comment]
Thank you @iliajie and @jcameron !

**Pull request merged**
