### PR TITLE
Fix to conditionally sent XFP header and fix `mod_headers` check

### PR DESCRIPTION
**Pull request by iliajie**
Hello Jamie!

This PR fixes ongoing issue as discussed [here](https://github.com/virtualmin/virtualmin-gpl/commit/68b828f18ffc6485a04c53e19ae849f449004911#r142691321).

### CODE REVIEW

**Comment by jcameron** [comment]
This isn't what we want though, because that header indicates if the *original* protocol was SSL, not the protocol from Apache to the backend.

**Comment by iliajie** [comment]
> This isn't what we want though, because that header indicates if the _original_ protocol was SSL, not the protocol from Apache to the backend.

Ah, you're right! What about this change then:

https://github.com/virtualmin/virtualmin-gpl/pull/821/files

**Comment by jcameron** [comment]
Thanks, looks good!

**Comment by iliajie** [comment]
Welcome!

**Pull request merged**
