### PR TITLE
Add a way to remove un-used database(s) from global feature's list #109

### PR DESCRIPTION
**Pull request by iliarostovtsev**
This PR addresses this https://github.com/virtualmin/virtualmin-gpl/issues/109#issuecomment-813775214

### CODE REVIEW

**Comment by jcameron** [comment]
I don't think this is a good idea, because if Postfix is installed but Webmin is looking in the wrong place for it, the user won't even know.

**Comment by iliarostovtsev** [comment]
Postfix? Did you mean to say PostgreSQL?

By default PostgreSQL is enabled in _acls_ so all will be seen and displayed as before, just as that admin capable user would have an opportunity to disable it, and only then it won't be displayed in Features and Plugins page. It's quite rational to me and provides the only way to control the display of core Virtualmin features.

**Comment by iliarostovtsev** [comment]
.. and besides, if Webmin is looking at the wrong place it's a bug or use of unsupported system. Nothing would work smoothly anyway in this case scenario.

**Comment by jcameron** [comment]
OK I see now .. the idea is good, but I prefer a different implementation which I've just checked in.

**Comment by iliarostovtsev** [comment]
Cool. Thanks. I'll give it a try tomorrow.

**Comment by iliarostovtsev** [comment]
> OK I see now .. the idea is good, but I prefer a different implementation which I've just checked in.

It works fine! I like the implementation more. Thank you.

I have a question though -- what else but post-installation wizard changes `$config{'mysql'}` and `$config{'postgres'}` config options?

I mean this check:
https://github.com/virtualmin/virtualmin-gpl/blob/0be3423407facbf97d39348a5d162b65c16ad807/edit_newfeatures.cgi#L23-L25

.. is config `mysql={1|0}` and `postgres={1|0}` is only set from post-installation wizard?

**Comment by jcameron** [comment]
Yes only the post-install wizard and the features and plugins page.

**Comment by iliarostovtsev** [comment]
So what would be the way to re-enable a feature that is no longer present on Features and Plugins page (was disabled)? Re-run post-installation wizard?

**Comment by jcameron** [comment]
Yes that would be the simplest way. There's a link on the left menu to re-run the wizard.

**Pull request closed without merging**
