### PR TITLE
Scripts are Webapps

### PR DESCRIPTION
**Pull request by iliajie**
Hello Jamie!

As we discussed earlier, I have changed the "Scripts" label to "Webapps" to better reflect the functionality. I have updated this in the language and help files, as well as all translations.

### CODE REVIEW

**Comment by jcameron** [comment]
This is a big change in wording! @swelljoe what do you think?

**Comment by swelljoe** [comment]
I don't like webapps (all in one word) either.

Web Apps or Applications would be better. Applications is probably my preference.

**Comment by swelljoe** [comment]
Web Apps is fine, though.

**Comment by iliajie** [comment]
Thanks for pointing this out, Joe. Fixed on the latest commit.

**Comment by jcameron** [comment]
Ok "Web Apps" it is then! Although I don't think we should rename any API commands or their output..

**Comment by iliajie** [comment]
Perhaps we could create a link?

**Comment by jcameron** [comment]
I'd rather not ... best to keep APIs stable, because we have no idea what scripts that use them exist out there.

**Comment by iliajie** [comment]
Can't we keep the API stable and backward-compatible with all old `-script` versions while using the new `-webapp` instead?

**Comment by iliajie** [comment]
Can't we keep the API stable and backward-compatible with all old API `-script` filenames while also using the new `-webapp`?

**Comment by jcameron** [comment]
I'd prefer not to, because even if we create symlinks the API commands include their own names in their output. Best not to make too many unnecessary changes.

**Comment by iliajie** [comment]
Alright, then we're good to move on.

**Comment by iliajie** [comment]
Although, shouldn't we at least mention in parentheses (web app) in help? I mean like this:

```
root@ubuntu24-pro:~# virtualmin | grep script
install-script            Install one third-party script (web app)
delete-script             Un-install one script (web app) from a virtual server
list-scripts              Display script (web app) installed into some virtual server
list-available-scripts    List known scripts (web apps)
```

**Comment by jcameron** [comment]
Sure that seems reasonable!

**Comment by iliajie** [comment]
> Sure that seems reasonable!

Okay, done https://github.com/virtualmin/virtualmin-gpl/pull/814/commits/613b4ba4949d9284a8faea3705ed573635f27424.

**Pull request merged**
