### PR TITLE
Fix to clear Dovecot config cache if creating and deleting on the same call

### PR DESCRIPTION
**Pull request by iliajie**
https://forum.virtualmin.com/t/re-lets-encrypt-apache-website-an-ipv6-dns-record-mydomain-org-with-address-1-exists-but-this-virtual-server-does-not-have-ipv6-enabled/125447/45?u=ilia

### CODE REVIEW

**Comment by jcameron** [comment]
No let's not do this, I'd prefer to actually fix this properly by making sure the cache is correct.

**Comment by iliajie** [comment]
Yeah, that's what I though too, and as I mentioned on the thread I thought it to be rather a work-around ..

**Comment by shoulders** [comment]
@jcameron and @iliajie 

I cannot work out if this should be closed because it was fixed another way instead of using the pull request

This is a couple of months old and maybe should be closed.

**Comment by jcameron** [comment]
We don't need this anymore because I fixed the underlying issue...

**Pull request closed without merging**
