### PR TITLE
Allow setting status collection interval to days

### PR DESCRIPTION
**Pull request by willnode**
Even though the manual say we can disable status collection, it is impractical since it handles more than just dashboard status.

I disable status collection on my machine since I rarely visits Virtualmin dashboard and it takes a lot of CPU. But disabling it also disables Let's Encrypt renewals, which is bad.

So it can't be disabled, but I also can't extend it more than 60 minutes.

This PR allows to extend it for up to 32 days (once a month) so Let's Encrypt renewals still works.

### CODE REVIEW

**Comment by iliajie** [comment]
Hello,

Thanks for your PR!

> Virtualmin dashboard and it takes a lot of CPU.

All the data on the Virtualmin dashboard is cached, so there’s no need to disable status collection. It's not the right approach. Sorry.

> So it can't be disabled, but I also can't extend it more than 60 minutes.

That’s rather a bit too complicated. I also don’t think it’s right to stop Let’s Encrypt renewals when status collection is off. We need to separate the logic for that. What do you think, Jamie?

**Comment by jcameron** [comment]
Seems like we need to look at the cause of CPU consumption if running this only once an hour is too expensive! How long does it run for on your system?

**Comment by willnode** [comment]
With host about 350 sites it's 40 seconds first time, then subsequent run is about 20 seconds.

**Comment by willnode** [comment]
Well I have slower system, it runs for 2 min 40 seconds first time, then 1 min 20 seconds subsequently

**Comment by willnode** [comment]
I'm suspect that most lengthy operation about this cron job is checking SSL renew. It's much expensive than you think.

I have an occurrence where it retries many domains at a time and kept failing due to customer has broken SSL setup somewhere along the way. Image this running every hour!

Even i have to code [my own scheduler](https://github.com/domcloud/bridge/blob/main/sudocleanssl.js) to disable renew if domains kept failing to renew for >24 hours.

**Comment by jcameron** [comment]
Wow that is pretty slow! Is it actually re-trying to renew the Let's Encrypt on every attempt?

**Comment by willnode** [comment]
I read some code here last time, it seems has some back-off mechanism to prevent hitting rate limit. 

Nonetheless, yes it keep retrying. I had couple occurences when the whole server is hitting LE rate limit in IP level until I code my own scheduler and SSL domain sharing.

**Comment by jcameron** [comment]
Yeah the rate limit is per domain, so if you had a large number of domains that are behind on their LE renewals it could cause problems. Does the LE service have a per-IP limit as well as per-domain?

**Comment by willnode** [comment]
Yes, 300 New Orders per account (basically it's whole server) per 3 hours. https://letsencrypt.org/docs/rate-limits/

**Comment by willnode** [comment]
I offer a kind of free hosting, if you wonder why.

**Comment by jcameron** [comment]
Odd, there's already code in Virtualmin which attempts to stay below 150 renewals per hour for this reason.

**Comment by willnode** [comment]
The limit inside `apply_letsencrypt_cert_renewals`? I think it is because it only count renewals inside scheduler, not counting new SSL issues and manually triggered renewals.

Anyway, this IP level limit is only happened rarely and it's been long time ago; i'm happy with my current setup.

I could better execute this PR by splitting the collectinfo.pl cronjob but that's a lot of changes.

**Comment by jcameron** [comment]
One thing you could try to lower the load from LE renewals is to reduce the number here : https://github.com/virtualmin/virtualmin-gpl/blob/master/feature-ssl.pl#L2917

Say down to 50 from the default of 300.

**Comment by willnode** [comment]
I think that will do. Thanks!

How about this PR? No longer valid? Or reduce to hourly cap?

**Comment by jcameron** [comment]
Let me know how it goes for you with a lower cap, and if that solves the issue maybe we can drop this PR.

**Comment by willnode** [comment]
Hello, after few days I think I can safely say i'm quite comfortable with 60 minutes interval. I think we can drop this.

Please separate the cronjob for status collection and SSL renewal if it possible, thank you!

**Pull request closed without merging**
