### PR TITLE
7.20.2

### PR DESCRIPTION
**Pull request by iliajie**
This is Virtualmin 7.20.2 release. All crucial changes were cherry-picked on to _master_ of 7.20.1 tagged release.

This can be used to create a new realease with the following log:

* Fix external DNS filter to consider CNAME and IPv6 records
* Fix not to trigger DNS filter for existing Let's Encrypt renewals
* Fix false positive message to move SSL certificate to default location
* FIx old documentation links

### CODE REVIEW

**Comment by iliajie** [comment]
This PR is not for merging! Only to make a new tagged release using 7.20.2 branch!

**Comment by jcameron** [comment]
Seems like there are merge conflicts?

**Comment by iliajie** [comment]
❗ Do not merge it! ❗

You just go to [Releases](https://github.com/virtualmin/virtualmin-gpl/releases/new) and create a new release using this branch with cherry picks on top of 7.20.1, e.g.:

image

**Comment by jcameron** [comment]
Ok done here : https://github.com/virtualmin/virtualmin-gpl/releases/tag/7.20.2

**Pull request closed without merging**
