### PR TITLE
Fix to prefix `other` envs vars to preven clashes

### PR DESCRIPTION
**Pull request by iliajie**

### CODE REVIEW

**Comment by iliajie** [comment]
@jcameron Jamie, please check this PR. `$ENV{'SCRIPT_NAME'}` is used by the `miniserv`.

**Comment by jcameron** [comment]
Won't this break users' existing scripts that depend on the old variables? Also, does it even matter if SCRIPT_NAME is overridden?

**Comment by iliajie** [comment]
> Won't this break users' existing scripts that depend on the old variables?

No, because it keeps old variables too.

> Also, does it even matter if SCRIPT_NAME is overridden?

Probably not, but should be expected to work! Nevertheless, it's not even set with the current code (i.e. `script_name`).

**Comment by jcameron** [comment]
Ok, thanks!

**Pull request merged**
