### PR TITLE
Add Sponsor button. Donation transparency and thanks.

### PR DESCRIPTION
**Pull request by chris001**

### CODE REVIEW

**Comment by chris001** [comment]
Moved from https://github.com/virtualmin/virtualmin-install/pull/10 because this is the main repo where users go to report issues with the software, and request features.

**Comment by chris001** [comment]
For this patch to actually work when merged, the Virtualmin github org or repo admin has to
1. Enable the github repo setting to accept Sponsors/donations,
2. Connect virtualmin org to opencollective, to get the awesome donation transparency features working on the main page of the repo in the README.

**Comment by chris001** [comment]
The drawback with running your own self hosted self managed donations page, and it's substantial, is, bigger donors, the corporate types that donate in the range of thousands of dollars, are only allowed to donate thru an external third party donations platform with a quarterly, professionally audited, public record of all the incoming donations and outgoing payments, like an OpenCollective.  Why?  Because their board of directors and shareholders, won't let them donate directly to an organization's self-managed self-run donations page, it's too risky to get in trouble, and it doesn't even get them anything in return for that taking risk, they move on to the next open source project that gets its donations thru an open external third party non profit operated and managed donations platform. that publishes all incoming and outgoing transactions and is itself checked for accuracy by professionals every quarter.  Correct this if it's wrong, logically, If we want to obtain bigger donations from these corporate donors, and we most definitely do, then we need to allow them to donate thru an acceptable external third party donations platform so that they'd be allowed to donate.  So, we'd need to register a free account for Virtualmin on an OpenCollective type of platform.  My question is this, What are your reasons, if any, for self coding, self maintaining, and self managing outgoing payments from, this donation page on the website?  Thanks!

**Comment by swelljoe** [comment]
"No." is a complete sentence. I have nothing else to say about it.

**Comment by chris001** [comment]
Joe, You're right!  You don’t owe anything to anyone — expect maybe respect to those who have earned it.  While sharing your reasons can be respectful of others' love for our common interest, this amazing software, plus, respect our tremendous appreciation for your significant, massive, contributions, and open the field for deeper understanding between others giving valuable time to be here, and maybe establish or strengthen bonds with this motley crew, you're absolutely right, it’s not a rule that you need to share your reasons with others, each and every time that they ask you to share.

We get it!  Sometimes you’re just too tired, you don’t want to, or you’re not sure of the reason your body is telling you to say "no". That’s okay, you're working a full time day job, and burnout is real.

And anybody who loves you or respects you will understand that!  We have mad love for you, Joe!

(and if they really need a reason, they’ll ask respectfully and be understanding when you don’t have one or can’t explain it.)

Joe, No man is an island.

I propose this:

Let's raise funds for the GPL software in two teams.   BOTH you using your page let's call this Team Joe.  AND Team Chris, me Marc and others, we raise funds thru an open collective page required by the bigger donors!

Your funds, PLUS my funds, equal more funding than either one  alone.

WITH NO ADDITIONAL ENERGY OR ATTENTION FROM YOU, JOE!

In the best interest of this software and its user community.... Let's do this!  Can we get a Yes, Joe!?

**Comment by swelljoe** [comment]
I do not know how else to say no. I'm not trying to negotiate with you, the answer is no, and your unwillingness to hear me and respect our decision on this is becoming a problem. Respecting boundaries is a baseline for achieving mutual respect, and I've set a boundary here, which you're refusing to respect or even acknowledge.

This really feels like you're actively trying to consume my time and energy. I don't want to argue with you. If you want to contribute to Virtualmin development, there are so many better ways to do it than adding more bureaucracy and confusion about who is able to accept donations for the project and where that money goes. I welcome help, but this isn't helping.

**Comment by chris001** [comment]
We hear what you said, however, without your actual reasons, it doesn't logically compute.  I think you're burned out from a full time job.  I think there's something you don't know about how easy these open platforms work, and you've leaped to conclusions and assumed the worst, their "bureaucracy" would be a burden on you.  What you don't know is, Paying out funds is as easy as logging into an online bank, enter the amount to pay, and the email address of the person, send.  It shows up automatically on the organization's public activity feed.

Change my mind.   Why in the world would you want to turn away hundreds or thousands of dollars per month for the benefit this software, from bigger donors who can only go thru an outside open platform.  You wouldn't even be involved in any way with that open platform funding, if you didn't want to be.  Maybe enough funds to add a person or two if you all want to, and as a result, improve the worldwide community of users' experience, they would absolutely welcome the improvements that come from more funding.  Joe, you wouldn't have to put any energy or attention on any of this fund raising or even payouts, probably someone could be found to handle that piece if you didn't want to.   Your donation page would continue to be compatible with generous individual users and private businesses who don't have the requirement public companies and organizations have, of giving thru a registered and audited outside transparent platform only.  For totally free, and with none of your energy or attention, more funding comes in from bigger donors, and the many many software users get substantial benefits.  Win-win.  You bring up a point, which I'd like to hear input from others.  @jcameron @iliajie hypothetically, if me and Marc were able to raise a monthly $500 - $1000, from corporate donors thru open collective, would you turn down that funding?  If yes, why?  If you'd accept it, in your opinion,  to what extent would it be a problem deciding where that money should go, for the benefit of the software and user community?

**Comment by swelljoe** [comment]
Chris, please just take no for an answer. I don't want to have to block you from the project.

**Pull request closed without merging**
