### PR TITLE
Navigation menu reorganization PR

### PR DESCRIPTION
**Pull request by iliajie**
This change is made in relation to https://github.com/virtualmin/virtualmin-gpl/issues/663. I haven't commited changes for the other Virtualmin modules yet, but I will tomorrow to ensure everything functions as expected.

Let's discuss this PR first! This is how it looks now:

image

image

image

image

Does the menu make more sense now?

### CODE REVIEW

**Comment by jcameron** [comment]
Will we also need plugin updates for this change, so that their menu items appear in the right place?

**Comment by iliajie** [comment]
Yes, we do and as I mentioned earlier I will just push the commits after we agree on the PR and merge it.

**Comment by jcameron** [comment]
What will happen if users update Virtualmin but not theme packages though? Will the UI break?

**Comment by iliajie** [comment]
If they install Webmin 2.104 then all icons will display properly. Prior Webmin versions will display default icon instead.

**Pull request merged**
