### PR TITLE
Require cgi only if mail is enabled

### PR DESCRIPTION
**Pull request by adbario**
Mail client auto-configuration requires active Apache module mod_cgi or mod_cgid. If mail is disabled on the server, cgi requirement shouldn't exist.

Issues #28 and #31

Also skip checking missing FTP shell if FTP in disabled.

### CODE REVIEW

**Comment by jcameron** [comment]
But CGI support is also needed for potentially running PHP scripts, webalizer, awstats and other functions.

**Comment by adbario** [comment]
Oh yes you're right, I didn't think of all these options. Anyway would be good to have some way to disable it, ie. I do have one server which only runs WordPress sites with PHP-FPM, no mail, webalizer or awstats, and no need for CGI. Would be great to be able to turn it off without hacking virtual-server-lib-funcs.pl manually after every Virtualmin update.

**Comment by jcameron** [comment]
In that case I'd just recommend enabled the cgi Apache module anyway - it will be cheap if it isn't used.

**Comment by adbario** [comment]
Sure that works, I'll do that or just turn off the check manually. Thanks!

**Pull request closed without merging**
