### PR TITLE
Fix to allow the root user to assign any shells

### PR DESCRIPTION
**Pull request by iliajie**
In continuation of https://github.com/virtualmin/virtualmin-gpl/pull/787#issuecomment-2073636834

### CODE REVIEW

**Comment by jcameron** [comment]
Hang on, I don't see why this is needed when the owner type is already passed into available_shells_menu for SSH users here : https://github.com/virtualmin/virtualmin-gpl/blob/master/edit_user.cgi#L97

**Comment by iliajie** [comment]
> Hang on, I don't see why this is needed when the owner type is already passed into available_shells_menu for SSH users here : https://github.com/virtualmin/virtualmin-gpl/blob/master/edit_user.cgi#L97

Because there is another one that is set to `mailbox` user here :

https://github.com/virtualmin/virtualmin-gpl/blob/master/edit_user.cgi#L814

**Comment by iliajie** [comment]
Anyway, here is the expected fix https://github.com/virtualmin/virtualmin-gpl/pull/789/commits/7e2579fa30370042e28c187f36ad6f4553efd89f.

**Comment by jcameron** [comment]
Ok that looks better ..thanks!

**Comment by iliajie** [comment]
> Ok that looks better ..thanks!

Alright! By the way, I didn't add it to `edit_defaults.cgi` page.

**Pull request closed without merging**
