### PR TITLE
Fix config link to lead to user interface section

### PR DESCRIPTION
**Pull request by iliajie**
Hi Jamie! As discussed here https://github.com/virtualmin/virtualmin-gpl/issues/751.

### CODE REVIEW

**Comment by iliajie** [comment]
I'd say, _no_,  as it would be more complicated and involve much more changes.

There is nothing wrong in modifying DOM, considering it's simple, works with all themes and doesn't create any theme-specific dependency.

**Comment by iliajie** [comment]
However, it would work if we could re-use existing config param in `header` sub, i.e. `$_[3]` and if set to a string (rather than `1`) then add it as part of a query..

**Comment by iliajie** [comment]
Okay, I have changed to pass params directly.

Depended PR is here https://github.com/webmin/webmin/pull/2098.

**Comment by jcameron** [comment]
Thanks for these patches!

**Pull request merged**
