### PR TITLE
Update host and domain default page

### PR DESCRIPTION
**Pull request by iliajie**
I have finally completed and _fully_ tested the change for updating the old domain default page.

The new page will have both dark and light palettes. It will also have disabled state and separate default pages for the host and domains.

**Dark palette** screenshots examples are here:

host - dark
domain - dark
domain disabled - dark

**Light palette** screenshots examples are here:

host - light
domain - light
domain disabled - light

**Live examples** can be checked here:

Host default page: [index-host-default.html](https://virtualmin.dev/index-host-default.html)
Domain default page: [index-domain-default.html](https://virtualmin.dev/index-domain-default.html)
Disabled domain page [index-disabled-default.html](https://virtualmin.dev/index-disabled-default.html)

### CODE REVIEW

**Comment by marclaporte** [comment]
WOW!

**Comment by chris001** [comment]
Excellent ⭐ ⭐ ⭐ ⭐ ⭐

**Comment by jcameron** [comment]
The code looks good to me!

@swelljoe any changes you want to make to the wording before I merge this?

**Comment by swelljoe** [comment]
I have a bunch of minor English language edits I'd like to make. I guess I can commit to the PR branch...

**Comment by iliajie** [comment]
> I have a bunch of minor English language edits I'd like to make (I'd rather just edit directly than try to explain all the differences in text). I guess I can commit to the PR branch...

Yes, of course. Just commit here!

**Comment by iliajie** [comment]
Thanks, Joe! All looks good!

**Pull request merged**
