### PR TITLE
Add `.well-known` location work with proxy enabled sites

### PR DESCRIPTION
**Pull request by iliajie**
Add `.well-known` location work with proxy enabled sites

### CODE REVIEW

**Comment by jcameron** [comment]
How will this behave for domains that already have `ProxyPass /.well-known/acme-challenge/ !` ?

**Comment by iliajie** [comment]
Those are meant to be added only on initial setup.

**Comment by iliajie** [comment]
.. therefore it makes no difference.

**Comment by jcameron** [comment]
Thanks for the patch!

**Pull request merged**
