### PR TITLE
support Aurora weirdness https://github.com/virtualmin/virtualmin-gpl/issues/4

### PR DESCRIPTION
**Pull request by versantus**
Change how MySQL password is set/updated to better support Aurora

### CODE REVIEW

**Comment by jcameron** [comment]
As mentioned on https://virtualmin.com/node/52366 , we can't use this patch as it would break other systems on which `set password` is the only reliable way to set the password correctly.

**Comment by swelljoe** [comment]
I guess we'd need this to be a separate code path that detects whether the db is Aurora or MySQL (I think MariaDB also works the same as MySQL).

**Comment by jcameron** [comment]
Note that this applies to any MySQL server that has the `--skip-name-resolve` flag set.

I've committed https://github.com/virtualmin/virtualmin-gpl/commit/fad53fbfb639f58739aeb811b25882788c65fe21 in an attempt to handle this case.

**Comment by versantus** [comment]
Thanks for your work so far on this. I'll try out that version and let you know how I get on.

**Pull request closed without merging**
